version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5692:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  app:
    build: .
    depends_on:
      - rabbitmq
      - mongodb
    links:
      - rabbitmq
      - mongodb
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      MONGO_URL: "mongodb://mongodb:27017"
    
volumes:
  rabbitmq-data:
  mongodb-data: